### ISSUE TITLE
Add a REST API to upload/fetch files

### ISSUE THREAD

**Issue by torben-fruechtenicht** [eightyfour/drag-king#14]
drag-king is missing a REST API which would allow for transferring files programmatically (e.g. from build jobs).

For example:
- Posting a file (as the request body) to DRAGKINGHOST/folderA/folderA1/folderA1a would upload the file to that location, either creating it or overwriting an existing one (maybe also add a "allowOverwrite" parameter for that). One file per request would be ok, no need to handle multiple files per request
- And a GET operation which would fetch a file from a directory
- Of course DELETE would be welcome, too

**Comment by eightyfour** [comment]
Hey, I've added the functionality you ask for. Please check out the latest version 0.2.0. I've also updated the documentation and added some curl examples.
